
package io.github.xiaoyureed.concurrentjava.other.distributed_java.connect_demo.remote_call.webservice.client.client_generate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Business", targetNamespace = "http://client.webservice.remote_call.connect_demo.distributed_java.other.concurrentjava.xiaoyureed.github.io/client_generate")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Business {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://client.webservice.remote_call.connect_demo.distributed_java.other.concurrentjava.xiaoyureed.github.io/client_generate/Business/echoRequest", output = "http://client.webservice.remote_call.connect_demo.distributed_java.other.concurrentjava.xiaoyureed.github.io/client_generate/Business/echoResponse")
    public String echo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
