server:
  port: 8080
spring:
  application:
    name: hibernate-validation
  datasource:
    url: jdbc:h2:mem:app  #;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      #use_sql_comments: true
      #show_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    generate-ddl:
  h2:
    console:
      enabled: true