spring:
  profiles:
    active: dev

---
server:
  port: 9000
spring:
  profiles: dev
  application:
    name: auth-server
  # h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: test
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
