server:
  port: 8080
spring:
  application:
    name: spring-boot-jpa
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath*:db/schema.sql
    data: classpath*:db/data.sql
    url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    #
    # init schema on startup, default to false
    # create 启动时删数据库中的表，然后创建，退出时不删除数据表
      #create-drop 启动时删数据库中的表，然后创建，退出时删除数据表 如果表不存在报错
    #update 如果启动时表格式不一致则更新表，原有数据保留
    #validate 项目启动表结构进行校验 如果不一致则报错
    #none 不处理
    #
    ## 和 generate-ddl (def to false) 关系: 都可以控制是否执行datasource.schema脚本，来初始化数据库结构,
    #    只要任意一个是可执行状态, 如 true, update .要想不执行，两者都必须是不可执行状态，比如false和none
    hibernate:
      ddl-auto: update
logging:
  level:
    io.github.xiaoyureed.springbootjpa: debug