#https://blog.csdn.net/yuru974882032/article/details/106749299/
server:
  port: 8080
spring:
  application:
    name: mybatis-plus-actable
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/test
    username: san
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
        trace: true
      path: /h2-console








