###
#   Database Settings
###
spring:
  datasource:
    # http://localhost:8080/console
    # jdbc:h2:file:c:/h2/example-app
    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql

  ###
  #   H2 Settings
  ###
  h2:
    console:
      # default to true
      enabled: true
      path: /console # default: /h2-console
      settings:
        trace: false
        # allow remote access?
        web-allow-others: false
