spring:
  application:
    name: rabbitmq-demo
  rabbitmq:
    host: localhost
    port: 5672
#    username: guest
#    password: guest
    virtual-host: / # 默认就是连接到 / 这个虚拟主机, docker 启动的 rabbitmq 若不指定默认就是 "/"虚拟主机
#    virtual-host: /vh_demo