server:
  port: 9010
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: true
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:9001/eureka/
spring:
  application:
    name: rabbitmq-demo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: / # default to /
#    virtual-host: /vh_demo